// This file was GENERATED by command:
//     pump.py new_binding.h.pump
// DO NOT EDIT BY HAND!!!

#ifndef SAUCE_SAUCE_INTERNAL_BINDINGS_NEW_BINDING_H_
#define SAUCE_SAUCE_INTERNAL_BINDINGS_NEW_BINDING_H_

#include <sauce/injector.h>
#include <sauce/memory.h>
#include <sauce/named.h>
#include <sauce/provider.h>
#include <sauce/internal/binding.h>
#include <sauce/internal/bindings/transparent_binding.h>
#include <sauce/internal/key.h>
#include <sauce/internal/type_id.h>

namespace sauce {
namespace internal {
namespace bindings {

template<typename Dependency, typename Scope, typename Constructor,
    typename Allocator>
class NewBinding;

template<typename Dependency, typename Scope, typename Impl, typename Allocator>
class NewBinding<Dependency, Scope, Impl(), Allocator>:
  public TransparentBinding<Dependency, Scope> {

  typedef typename Key<Dependency>::Iface Iface;
  typedef typename Key<Dependency>::Ptr Ptr;
  typedef typename Binding<Dependency>::BindingPtr BindingPtr;
  typedef typename Allocator::template rebind<Impl>::other ImplAllocator;
  typedef NewBinding<Dependency, Scope, Impl(), Allocator> New;
  typedef DisposalDeleter<Iface, New> Deleter;

  friend class DisposalDeleter<Iface, New>;

  mutable ImplAllocator allocator;

  /**
   * Provide an Iface.
   *
   * A naked instance pointer is allocated and wrapped in a shared_ptr.  It is
   * also given a custom deleter, to dispose of the naked pointer with
   * dispose(Iface *).
   */
 Ptr provide(BindingPtr binding, InjectorPtr) const {
    Deleter deleter(sauce::static_pointer_cast<New>(binding));
    Impl * impl = allocator.allocate(1);
    Ptr provided(new(impl) Impl(), deleter);
    return provided;
  }

  void validateAcyclic(InjectorPtr, TypeIds &) const {}

  void dispose(Iface * iface) const {
    Impl * impl = static_cast<Impl *>(iface);
    impl->~Impl(); // Must not throw
    allocator.deallocate(impl, 1);
  }

};

template<typename Dependency, typename Scope, typename Impl,
    typename Allocator, typename A1>
class NewBinding<Dependency, Scope, Impl(A1), Allocator>:
  public TransparentBinding<Dependency, Scope> {

  typedef typename Key<Dependency>::Iface Iface;
  typedef typename Key<Dependency>::Ptr Ptr;
  typedef typename Binding<Dependency>::BindingPtr BindingPtr;
  typedef typename Allocator::template rebind<Impl>::other ImplAllocator;
  typedef NewBinding<Dependency, Scope, Impl(A1), Allocator> New;
  typedef DisposalDeleter<Iface, New> Deleter;

  friend class DisposalDeleter<Iface, New>;

  mutable ImplAllocator allocator;

  /**
   * Provide an Iface.
   *
   * A naked instance pointer is allocated and wrapped in a shared_ptr.  It is
   * also given a custom deleter, to dispose of the naked pointer with
   * dispose(Iface *).
   */
 Ptr provide(BindingPtr binding, InjectorPtr injector) const {
    typename Key<A1>::Ptr a1(this->template getDependency<A1>(injector));
    Deleter deleter(sauce::static_pointer_cast<New>(binding));
    Impl * impl = allocator.allocate(1);
    Ptr provided(new(impl) Impl(a1), deleter);
    return provided;
  }

  void validateAcyclic(InjectorPtr injector, TypeIds & ids) const {
    this->template validateAcyclicos<A1>(injector, ids);
  }

  void dispose(Iface * iface) const {
    Impl * impl = static_cast<Impl *>(iface);
    impl->~Impl(); // Must not throw
    allocator.deallocate(impl, 1);
  }

};

template<typename Dependency, typename Scope, typename Impl,
    typename Allocator, typename A1, typename A2>
class NewBinding<Dependency, Scope, Impl(A1, A2), Allocator>:
  public TransparentBinding<Dependency, Scope> {

  typedef typename Key<Dependency>::Iface Iface;
  typedef typename Key<Dependency>::Ptr Ptr;
  typedef typename Binding<Dependency>::BindingPtr BindingPtr;
  typedef typename Allocator::template rebind<Impl>::other ImplAllocator;
  typedef NewBinding<Dependency, Scope, Impl(A1, A2), Allocator> New;
  typedef DisposalDeleter<Iface, New> Deleter;

  friend class DisposalDeleter<Iface, New>;

  mutable ImplAllocator allocator;

  /**
   * Provide an Iface.
   *
   * A naked instance pointer is allocated and wrapped in a shared_ptr.  It is
   * also given a custom deleter, to dispose of the naked pointer with
   * dispose(Iface *).
   */
 Ptr provide(BindingPtr binding, InjectorPtr injector) const {
    typename Key<A1>::Ptr a1(this->template getDependency<A1>(injector));
    typename Key<A2>::Ptr a2(this->template getDependency<A2>(injector));
    Deleter deleter(sauce::static_pointer_cast<New>(binding));
    Impl * impl = allocator.allocate(1);
    Ptr provided(new(impl) Impl(a1, a2), deleter);
    return provided;
  }

  void validateAcyclic(InjectorPtr injector, TypeIds & ids) const {
    this->template validateAcyclicos<A1>(injector, ids);
    this->template validateAcyclicos<A2>(injector, ids);
  }

  void dispose(Iface * iface) const {
    Impl * impl = static_cast<Impl *>(iface);
    impl->~Impl(); // Must not throw
    allocator.deallocate(impl, 1);
  }

};

template<typename Dependency, typename Scope, typename Impl,
    typename Allocator, typename A1, typename A2, typename A3>
class NewBinding<Dependency, Scope, Impl(A1, A2, A3), Allocator>:
  public TransparentBinding<Dependency, Scope> {

  typedef typename Key<Dependency>::Iface Iface;
  typedef typename Key<Dependency>::Ptr Ptr;
  typedef typename Binding<Dependency>::BindingPtr BindingPtr;
  typedef typename Allocator::template rebind<Impl>::other ImplAllocator;
  typedef NewBinding<Dependency, Scope, Impl(A1, A2, A3), Allocator> New;
  typedef DisposalDeleter<Iface, New> Deleter;

  friend class DisposalDeleter<Iface, New>;

  mutable ImplAllocator allocator;

  /**
   * Provide an Iface.
   *
   * A naked instance pointer is allocated and wrapped in a shared_ptr.  It is
   * also given a custom deleter, to dispose of the naked pointer with
   * dispose(Iface *).
   */
 Ptr provide(BindingPtr binding, InjectorPtr injector) const {
    typename Key<A1>::Ptr a1(this->template getDependency<A1>(injector));
    typename Key<A2>::Ptr a2(this->template getDependency<A2>(injector));
    typename Key<A3>::Ptr a3(this->template getDependency<A3>(injector));
    Deleter deleter(sauce::static_pointer_cast<New>(binding));
    Impl * impl = allocator.allocate(1);
    Ptr provided(new(impl) Impl(a1, a2, a3), deleter);
    return provided;
  }

  void validateAcyclic(InjectorPtr injector, TypeIds & ids) const {
    this->template validateAcyclicos<A1>(injector, ids);
    this->template validateAcyclicos<A2>(injector, ids);
    this->template validateAcyclicos<A3>(injector, ids);
  }

  void dispose(Iface * iface) const {
    Impl * impl = static_cast<Impl *>(iface);
    impl->~Impl(); // Must not throw
    allocator.deallocate(impl, 1);
  }

};

template<typename Dependency, typename Scope, typename Impl,
    typename Allocator, typename A1, typename A2, typename A3, typename A4>
class NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4), Allocator>:
  public TransparentBinding<Dependency, Scope> {

  typedef typename Key<Dependency>::Iface Iface;
  typedef typename Key<Dependency>::Ptr Ptr;
  typedef typename Binding<Dependency>::BindingPtr BindingPtr;
  typedef typename Allocator::template rebind<Impl>::other ImplAllocator;
  typedef NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4), Allocator> New;
  typedef DisposalDeleter<Iface, New> Deleter;

  friend class DisposalDeleter<Iface, New>;

  mutable ImplAllocator allocator;

  /**
   * Provide an Iface.
   *
   * A naked instance pointer is allocated and wrapped in a shared_ptr.  It is
   * also given a custom deleter, to dispose of the naked pointer with
   * dispose(Iface *).
   */
 Ptr provide(BindingPtr binding, InjectorPtr injector) const {
    typename Key<A1>::Ptr a1(this->template getDependency<A1>(injector));
    typename Key<A2>::Ptr a2(this->template getDependency<A2>(injector));
    typename Key<A3>::Ptr a3(this->template getDependency<A3>(injector));
    typename Key<A4>::Ptr a4(this->template getDependency<A4>(injector));
    Deleter deleter(sauce::static_pointer_cast<New>(binding));
    Impl * impl = allocator.allocate(1);
    Ptr provided(new(impl) Impl(a1, a2, a3, a4), deleter);
    return provided;
  }

  void validateAcyclic(InjectorPtr injector, TypeIds & ids) const {
    this->template validateAcyclicos<A1>(injector, ids);
    this->template validateAcyclicos<A2>(injector, ids);
    this->template validateAcyclicos<A3>(injector, ids);
    this->template validateAcyclicos<A4>(injector, ids);
  }

  void dispose(Iface * iface) const {
    Impl * impl = static_cast<Impl *>(iface);
    impl->~Impl(); // Must not throw
    allocator.deallocate(impl, 1);
  }

};

template<typename Dependency, typename Scope, typename Impl,
    typename Allocator, typename A1, typename A2, typename A3, typename A4,
    typename A5>
class NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5), Allocator>:
  public TransparentBinding<Dependency, Scope> {

  typedef typename Key<Dependency>::Iface Iface;
  typedef typename Key<Dependency>::Ptr Ptr;
  typedef typename Binding<Dependency>::BindingPtr BindingPtr;
  typedef typename Allocator::template rebind<Impl>::other ImplAllocator;
  typedef NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5),
      Allocator> New;
  typedef DisposalDeleter<Iface, New> Deleter;

  friend class DisposalDeleter<Iface, New>;

  mutable ImplAllocator allocator;

  /**
   * Provide an Iface.
   *
   * A naked instance pointer is allocated and wrapped in a shared_ptr.  It is
   * also given a custom deleter, to dispose of the naked pointer with
   * dispose(Iface *).
   */
 Ptr provide(BindingPtr binding, InjectorPtr injector) const {
    typename Key<A1>::Ptr a1(this->template getDependency<A1>(injector));
    typename Key<A2>::Ptr a2(this->template getDependency<A2>(injector));
    typename Key<A3>::Ptr a3(this->template getDependency<A3>(injector));
    typename Key<A4>::Ptr a4(this->template getDependency<A4>(injector));
    typename Key<A5>::Ptr a5(this->template getDependency<A5>(injector));
    Deleter deleter(sauce::static_pointer_cast<New>(binding));
    Impl * impl = allocator.allocate(1);
    Ptr provided(new(impl) Impl(a1, a2, a3, a4, a5), deleter);
    return provided;
  }

  void validateAcyclic(InjectorPtr injector, TypeIds & ids) const {
    this->template validateAcyclicos<A1>(injector, ids);
    this->template validateAcyclicos<A2>(injector, ids);
    this->template validateAcyclicos<A3>(injector, ids);
    this->template validateAcyclicos<A4>(injector, ids);
    this->template validateAcyclicos<A5>(injector, ids);
  }

  void dispose(Iface * iface) const {
    Impl * impl = static_cast<Impl *>(iface);
    impl->~Impl(); // Must not throw
    allocator.deallocate(impl, 1);
  }

};

template<typename Dependency, typename Scope, typename Impl,
    typename Allocator, typename A1, typename A2, typename A3, typename A4,
    typename A5, typename A6>
class NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5, A6), Allocator>:
  public TransparentBinding<Dependency, Scope> {

  typedef typename Key<Dependency>::Iface Iface;
  typedef typename Key<Dependency>::Ptr Ptr;
  typedef typename Binding<Dependency>::BindingPtr BindingPtr;
  typedef typename Allocator::template rebind<Impl>::other ImplAllocator;
  typedef NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5, A6),
      Allocator> New;
  typedef DisposalDeleter<Iface, New> Deleter;

  friend class DisposalDeleter<Iface, New>;

  mutable ImplAllocator allocator;

  /**
   * Provide an Iface.
   *
   * A naked instance pointer is allocated and wrapped in a shared_ptr.  It is
   * also given a custom deleter, to dispose of the naked pointer with
   * dispose(Iface *).
   */
 Ptr provide(BindingPtr binding, InjectorPtr injector) const {
    typename Key<A1>::Ptr a1(this->template getDependency<A1>(injector));
    typename Key<A2>::Ptr a2(this->template getDependency<A2>(injector));
    typename Key<A3>::Ptr a3(this->template getDependency<A3>(injector));
    typename Key<A4>::Ptr a4(this->template getDependency<A4>(injector));
    typename Key<A5>::Ptr a5(this->template getDependency<A5>(injector));
    typename Key<A6>::Ptr a6(this->template getDependency<A6>(injector));
    Deleter deleter(sauce::static_pointer_cast<New>(binding));
    Impl * impl = allocator.allocate(1);
    Ptr provided(new(impl) Impl(a1, a2, a3, a4, a5, a6), deleter);
    return provided;
  }

  void validateAcyclic(InjectorPtr injector, TypeIds & ids) const {
    this->template validateAcyclicos<A1>(injector, ids);
    this->template validateAcyclicos<A2>(injector, ids);
    this->template validateAcyclicos<A3>(injector, ids);
    this->template validateAcyclicos<A4>(injector, ids);
    this->template validateAcyclicos<A5>(injector, ids);
    this->template validateAcyclicos<A6>(injector, ids);
  }

  void dispose(Iface * iface) const {
    Impl * impl = static_cast<Impl *>(iface);
    impl->~Impl(); // Must not throw
    allocator.deallocate(impl, 1);
  }

};

template<typename Dependency, typename Scope, typename Impl,
    typename Allocator, typename A1, typename A2, typename A3, typename A4,
    typename A5, typename A6, typename A7>
class NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5, A6, A7),
    Allocator>:
  public TransparentBinding<Dependency, Scope> {

  typedef typename Key<Dependency>::Iface Iface;
  typedef typename Key<Dependency>::Ptr Ptr;
  typedef typename Binding<Dependency>::BindingPtr BindingPtr;
  typedef typename Allocator::template rebind<Impl>::other ImplAllocator;
  typedef NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5, A6, A7),
      Allocator> New;
  typedef DisposalDeleter<Iface, New> Deleter;

  friend class DisposalDeleter<Iface, New>;

  mutable ImplAllocator allocator;

  /**
   * Provide an Iface.
   *
   * A naked instance pointer is allocated and wrapped in a shared_ptr.  It is
   * also given a custom deleter, to dispose of the naked pointer with
   * dispose(Iface *).
   */
 Ptr provide(BindingPtr binding, InjectorPtr injector) const {
    typename Key<A1>::Ptr a1(this->template getDependency<A1>(injector));
    typename Key<A2>::Ptr a2(this->template getDependency<A2>(injector));
    typename Key<A3>::Ptr a3(this->template getDependency<A3>(injector));
    typename Key<A4>::Ptr a4(this->template getDependency<A4>(injector));
    typename Key<A5>::Ptr a5(this->template getDependency<A5>(injector));
    typename Key<A6>::Ptr a6(this->template getDependency<A6>(injector));
    typename Key<A7>::Ptr a7(this->template getDependency<A7>(injector));
    Deleter deleter(sauce::static_pointer_cast<New>(binding));
    Impl * impl = allocator.allocate(1);
    Ptr provided(new(impl) Impl(a1, a2, a3, a4, a5, a6, a7), deleter);
    return provided;
  }

  void validateAcyclic(InjectorPtr injector, TypeIds & ids) const {
    this->template validateAcyclicos<A1>(injector, ids);
    this->template validateAcyclicos<A2>(injector, ids);
    this->template validateAcyclicos<A3>(injector, ids);
    this->template validateAcyclicos<A4>(injector, ids);
    this->template validateAcyclicos<A5>(injector, ids);
    this->template validateAcyclicos<A6>(injector, ids);
    this->template validateAcyclicos<A7>(injector, ids);
  }

  void dispose(Iface * iface) const {
    Impl * impl = static_cast<Impl *>(iface);
    impl->~Impl(); // Must not throw
    allocator.deallocate(impl, 1);
  }

};

template<typename Dependency, typename Scope, typename Impl,
    typename Allocator, typename A1, typename A2, typename A3, typename A4,
    typename A5, typename A6, typename A7, typename A8>
class NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5, A6, A7, A8),
    Allocator>:
  public TransparentBinding<Dependency, Scope> {

  typedef typename Key<Dependency>::Iface Iface;
  typedef typename Key<Dependency>::Ptr Ptr;
  typedef typename Binding<Dependency>::BindingPtr BindingPtr;
  typedef typename Allocator::template rebind<Impl>::other ImplAllocator;
  typedef NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5, A6, A7, A8),
      Allocator> New;
  typedef DisposalDeleter<Iface, New> Deleter;

  friend class DisposalDeleter<Iface, New>;

  mutable ImplAllocator allocator;

  /**
   * Provide an Iface.
   *
   * A naked instance pointer is allocated and wrapped in a shared_ptr.  It is
   * also given a custom deleter, to dispose of the naked pointer with
   * dispose(Iface *).
   */
 Ptr provide(BindingPtr binding, InjectorPtr injector) const {
    typename Key<A1>::Ptr a1(this->template getDependency<A1>(injector));
    typename Key<A2>::Ptr a2(this->template getDependency<A2>(injector));
    typename Key<A3>::Ptr a3(this->template getDependency<A3>(injector));
    typename Key<A4>::Ptr a4(this->template getDependency<A4>(injector));
    typename Key<A5>::Ptr a5(this->template getDependency<A5>(injector));
    typename Key<A6>::Ptr a6(this->template getDependency<A6>(injector));
    typename Key<A7>::Ptr a7(this->template getDependency<A7>(injector));
    typename Key<A8>::Ptr a8(this->template getDependency<A8>(injector));
    Deleter deleter(sauce::static_pointer_cast<New>(binding));
    Impl * impl = allocator.allocate(1);
    Ptr provided(new(impl) Impl(a1, a2, a3, a4, a5, a6, a7, a8), deleter);
    return provided;
  }

  void validateAcyclic(InjectorPtr injector, TypeIds & ids) const {
    this->template validateAcyclicos<A1>(injector, ids);
    this->template validateAcyclicos<A2>(injector, ids);
    this->template validateAcyclicos<A3>(injector, ids);
    this->template validateAcyclicos<A4>(injector, ids);
    this->template validateAcyclicos<A5>(injector, ids);
    this->template validateAcyclicos<A6>(injector, ids);
    this->template validateAcyclicos<A7>(injector, ids);
    this->template validateAcyclicos<A8>(injector, ids);
  }

  void dispose(Iface * iface) const {
    Impl * impl = static_cast<Impl *>(iface);
    impl->~Impl(); // Must not throw
    allocator.deallocate(impl, 1);
  }

};

template<typename Dependency, typename Scope, typename Impl,
    typename Allocator, typename A1, typename A2, typename A3, typename A4,
    typename A5, typename A6, typename A7, typename A8, typename A9>
class NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5, A6, A7, A8, A9),
    Allocator>:
  public TransparentBinding<Dependency, Scope> {

  typedef typename Key<Dependency>::Iface Iface;
  typedef typename Key<Dependency>::Ptr Ptr;
  typedef typename Binding<Dependency>::BindingPtr BindingPtr;
  typedef typename Allocator::template rebind<Impl>::other ImplAllocator;
  typedef NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5, A6, A7, A8,
      A9), Allocator> New;
  typedef DisposalDeleter<Iface, New> Deleter;

  friend class DisposalDeleter<Iface, New>;

  mutable ImplAllocator allocator;

  /**
   * Provide an Iface.
   *
   * A naked instance pointer is allocated and wrapped in a shared_ptr.  It is
   * also given a custom deleter, to dispose of the naked pointer with
   * dispose(Iface *).
   */
 Ptr provide(BindingPtr binding, InjectorPtr injector) const {
    typename Key<A1>::Ptr a1(this->template getDependency<A1>(injector));
    typename Key<A2>::Ptr a2(this->template getDependency<A2>(injector));
    typename Key<A3>::Ptr a3(this->template getDependency<A3>(injector));
    typename Key<A4>::Ptr a4(this->template getDependency<A4>(injector));
    typename Key<A5>::Ptr a5(this->template getDependency<A5>(injector));
    typename Key<A6>::Ptr a6(this->template getDependency<A6>(injector));
    typename Key<A7>::Ptr a7(this->template getDependency<A7>(injector));
    typename Key<A8>::Ptr a8(this->template getDependency<A8>(injector));
    typename Key<A9>::Ptr a9(this->template getDependency<A9>(injector));
    Deleter deleter(sauce::static_pointer_cast<New>(binding));
    Impl * impl = allocator.allocate(1);
    Ptr provided(new(impl) Impl(a1, a2, a3, a4, a5, a6, a7, a8, a9), deleter);
    return provided;
  }

  void validateAcyclic(InjectorPtr injector, TypeIds & ids) const {
    this->template validateAcyclicos<A1>(injector, ids);
    this->template validateAcyclicos<A2>(injector, ids);
    this->template validateAcyclicos<A3>(injector, ids);
    this->template validateAcyclicos<A4>(injector, ids);
    this->template validateAcyclicos<A5>(injector, ids);
    this->template validateAcyclicos<A6>(injector, ids);
    this->template validateAcyclicos<A7>(injector, ids);
    this->template validateAcyclicos<A8>(injector, ids);
    this->template validateAcyclicos<A9>(injector, ids);
  }

  void dispose(Iface * iface) const {
    Impl * impl = static_cast<Impl *>(iface);
    impl->~Impl(); // Must not throw
    allocator.deallocate(impl, 1);
  }

};

template<typename Dependency, typename Scope, typename Impl,
    typename Allocator, typename A1, typename A2, typename A3, typename A4,
    typename A5, typename A6, typename A7, typename A8, typename A9,
    typename A10>
class NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5, A6, A7, A8, A9,
    A10), Allocator>:
  public TransparentBinding<Dependency, Scope> {

  typedef typename Key<Dependency>::Iface Iface;
  typedef typename Key<Dependency>::Ptr Ptr;
  typedef typename Binding<Dependency>::BindingPtr BindingPtr;
  typedef typename Allocator::template rebind<Impl>::other ImplAllocator;
  typedef NewBinding<Dependency, Scope, Impl(A1, A2, A3, A4, A5, A6, A7, A8,
      A9, A10), Allocator> New;
  typedef DisposalDeleter<Iface, New> Deleter;

  friend class DisposalDeleter<Iface, New>;

  mutable ImplAllocator allocator;

  /**
   * Provide an Iface.
   *
   * A naked instance pointer is allocated and wrapped in a shared_ptr.  It is
   * also given a custom deleter, to dispose of the naked pointer with
   * dispose(Iface *).
   */
 Ptr provide(BindingPtr binding, InjectorPtr injector) const {
    typename Key<A1>::Ptr a1(this->template getDependency<A1>(injector));
    typename Key<A2>::Ptr a2(this->template getDependency<A2>(injector));
    typename Key<A3>::Ptr a3(this->template getDependency<A3>(injector));
    typename Key<A4>::Ptr a4(this->template getDependency<A4>(injector));
    typename Key<A5>::Ptr a5(this->template getDependency<A5>(injector));
    typename Key<A6>::Ptr a6(this->template getDependency<A6>(injector));
    typename Key<A7>::Ptr a7(this->template getDependency<A7>(injector));
    typename Key<A8>::Ptr a8(this->template getDependency<A8>(injector));
    typename Key<A9>::Ptr a9(this->template getDependency<A9>(injector));
    typename Key<A10>::Ptr a10(this->template getDependency<A10>(injector));
    Deleter deleter(sauce::static_pointer_cast<New>(binding));
    Impl * impl = allocator.allocate(1);
    Ptr provided(new(impl) Impl(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10),
        deleter);
    return provided;
  }

  void validateAcyclic(InjectorPtr injector, TypeIds & ids) const {
    this->template validateAcyclicos<A1>(injector, ids);
    this->template validateAcyclicos<A2>(injector, ids);
    this->template validateAcyclicos<A3>(injector, ids);
    this->template validateAcyclicos<A4>(injector, ids);
    this->template validateAcyclicos<A5>(injector, ids);
    this->template validateAcyclicos<A6>(injector, ids);
    this->template validateAcyclicos<A7>(injector, ids);
    this->template validateAcyclicos<A8>(injector, ids);
    this->template validateAcyclicos<A9>(injector, ids);
    this->template validateAcyclicos<A10>(injector, ids);
  }

  void dispose(Iface * iface) const {
    Impl * impl = static_cast<Impl *>(iface);
    impl->~Impl(); // Must not throw
    allocator.deallocate(impl, 1);
  }

};

}
}

namespace i = ::sauce::internal;
namespace b = ::sauce::internal::bindings;

}

#endif // SAUCE_SAUCE_INTERNAL_BINDINGS_NEW_BINDING_H_
