// This file was GENERATED by command:
//     pump.py generated_bindings.h.pump
// DO NOT EDIT BY HAND!!!

#ifndef SAUCE_SAUCE_INTERNAL_GENERATED_BINDINGS_H_
#define SAUCE_SAUCE_INTERNAL_GENERATED_BINDINGS_H_

namespace sauce { namespace internal { namespace bindings {

  template<typename Injector, class Iface, typename Constructor>
  struct New;

  template<typename Injector, class Iface, class Impl>
  struct New<Injector, Iface, Impl()> {
    static Impl * provide(Injector & injector) {
      return new Impl();
    };

    static void dispose(Injector & injector, Iface * iface) {
      // TODO: make test prove this delete is required..
      // delete iface;
    };
  };

  template<typename Injector, class Iface, class Impl, typename A1>
  struct New<Injector, Iface, Impl(A1)> {
    static Impl * provide(Injector & injector) {
      return new Impl(injector.template provide<A1>());
    };

    static void dispose(Injector & injector, Iface * iface) {
      // TODO: make test prove this delete is required..
      // delete iface;
    };
  };

  template<typename Injector, class Iface, class Impl, typename A1, typename A2>
  struct New<Injector, Iface, Impl(A1, A2)> {
    static Impl * provide(Injector & injector) {
      return new Impl(injector.template provide<A1>(),
          injector.template provide<A2>());
    };

    static void dispose(Injector & injector, Iface * iface) {
      // TODO: make test prove this delete is required..
      // delete iface;
    };
  };

  template<typename Injector, class Iface, class Impl, typename A1,
      typename A2, typename A3>
  struct New<Injector, Iface, Impl(A1, A2, A3)> {
    static Impl * provide(Injector & injector) {
      return new Impl(injector.template provide<A1>(),
          injector.template provide<A2>(), injector.template provide<A3>());
    };

    static void dispose(Injector & injector, Iface * iface) {
      // TODO: make test prove this delete is required..
      // delete iface;
    };
  };

  template<typename Injector, class Iface, class Impl, typename A1,
      typename A2, typename A3, typename A4>
  struct New<Injector, Iface, Impl(A1, A2, A3, A4)> {
    static Impl * provide(Injector & injector) {
      return new Impl(injector.template provide<A1>(),
          injector.template provide<A2>(), injector.template provide<A3>(),
          injector.template provide<A4>());
    };

    static void dispose(Injector & injector, Iface * iface) {
      // TODO: make test prove this delete is required..
      // delete iface;
    };
  };

  template<typename Injector, class Iface, class Impl, typename A1,
      typename A2, typename A3, typename A4, typename A5>
  struct New<Injector, Iface, Impl(A1, A2, A3, A4, A5)> {
    static Impl * provide(Injector & injector) {
      return new Impl(injector.template provide<A1>(),
          injector.template provide<A2>(), injector.template provide<A3>(),
          injector.template provide<A4>(), injector.template provide<A5>());
    };

    static void dispose(Injector & injector, Iface * iface) {
      // TODO: make test prove this delete is required..
      // delete iface;
    };
  };

  template<typename Injector, class Iface, class Impl, typename A1,
      typename A2, typename A3, typename A4, typename A5, typename A6>
  struct New<Injector, Iface, Impl(A1, A2, A3, A4, A5, A6)> {
    static Impl * provide(Injector & injector) {
      return new Impl(injector.template provide<A1>(),
          injector.template provide<A2>(), injector.template provide<A3>(),
          injector.template provide<A4>(), injector.template provide<A5>(),
          injector.template provide<A6>());
    };

    static void dispose(Injector & injector, Iface * iface) {
      // TODO: make test prove this delete is required..
      // delete iface;
    };
  };

  template<typename Injector, class Iface, class Impl, typename A1,
      typename A2, typename A3, typename A4, typename A5, typename A6,
      typename A7>
  struct New<Injector, Iface, Impl(A1, A2, A3, A4, A5, A6, A7)> {
    static Impl * provide(Injector & injector) {
      return new Impl(injector.template provide<A1>(),
          injector.template provide<A2>(), injector.template provide<A3>(),
          injector.template provide<A4>(), injector.template provide<A5>(),
          injector.template provide<A6>(), injector.template provide<A7>());
    };

    static void dispose(Injector & injector, Iface * iface) {
      // TODO: make test prove this delete is required..
      // delete iface;
    };
  };

  template<typename Injector, class Iface, class Impl, typename A1,
      typename A2, typename A3, typename A4, typename A5, typename A6,
      typename A7, typename A8>
  struct New<Injector, Iface, Impl(A1, A2, A3, A4, A5, A6, A7, A8)> {
    static Impl * provide(Injector & injector) {
      return new Impl(injector.template provide<A1>(),
          injector.template provide<A2>(), injector.template provide<A3>(),
          injector.template provide<A4>(), injector.template provide<A5>(),
          injector.template provide<A6>(), injector.template provide<A7>(),
          injector.template provide<A8>());
    };

    static void dispose(Injector & injector, Iface * iface) {
      // TODO: make test prove this delete is required..
      // delete iface;
    };
  };

  template<typename Injector, class Iface, class Impl, typename A1,
      typename A2, typename A3, typename A4, typename A5, typename A6,
      typename A7, typename A8, typename A9>
  struct New<Injector, Iface, Impl(A1, A2, A3, A4, A5, A6, A7, A8, A9)> {
    static Impl * provide(Injector & injector) {
      return new Impl(injector.template provide<A1>(),
          injector.template provide<A2>(), injector.template provide<A3>(),
          injector.template provide<A4>(), injector.template provide<A5>(),
          injector.template provide<A6>(), injector.template provide<A7>(),
          injector.template provide<A8>(), injector.template provide<A9>());
    };

    static void dispose(Injector & injector, Iface * iface) {
      // TODO: make test prove this delete is required..
      // delete iface;
    };
  };

  template<typename Injector, class Iface, class Impl, typename A1,
      typename A2, typename A3, typename A4, typename A5, typename A6,
      typename A7, typename A8, typename A9, typename A10>
  struct New<Injector, Iface, Impl(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)> {
    static Impl * provide(Injector & injector) {
      return new Impl(injector.template provide<A1>(),
          injector.template provide<A2>(), injector.template provide<A3>(),
          injector.template provide<A4>(), injector.template provide<A5>(),
          injector.template provide<A6>(), injector.template provide<A7>(),
          injector.template provide<A8>(), injector.template provide<A9>(),
          injector.template provide<A10>());
    };

    static void dispose(Injector & injector, Iface * iface) {
      // TODO: make test prove this delete is required..
      // delete iface;
    };
  };

} } } // namespace bindings, namespace internal, namespace sauce

#endif
