#! /bin/bash

set -e
set -x

date
uname -a

# Get the compiler version
cl

export CC="./cccl"
export CXX="./cccl"
export LD="./cccl"

export CXXFLAGS="--cccl-verbose /EHsc"
export LDFLAGS="--cccl-verbose --cccl-link /entry:mainCRTStartup"

cd /cygdrive/c/projects/sauce

# Appveyor (insanely?) doesn't give us a stdin here, so fake one.
exec 0</dev/null

autoreconf -vi
./configure
make check || (cat test-suite.log; false)
