#! /bin/bash

set -e
set -x

date
uname -a

# Install packages
sudo apt-get install -y \
  autoconf              \
  automake              \
  g++                   \
  libtool

autoreconf -vi
./configure
make check
